/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica_final.Principal.interfaces;

import com.mycompany.practica_final.Principal.archivos.LectorArchivo;
import com.mycompany.practica_final.Principal.archivos.LlenadoTabla;
import com.mycompany.practica_final.Principal.principal.AlmacenadorInfo;
import com.mycompany.practica_final.Principal.tokens.Separador_Token;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.UndoManager;

/**
 *
 * @author nroda
 */
public class Editor extends javax.swing.JFrame {

    /**
     * Creates new form Editor
     */
    private String textoGuardado = "";
    Copiar_Pegar cyp;
    Separador_Token stk;
    protected UndoManager hyd = new UndoManager();

    public Editor() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        cyp = new Copiar_Pegar();
        this.jTextArea1.getDocument().addUndoableEditListener(hyd);
        Contador_FC fyc = new Contador_FC(this.jTextArea1, this.jLabel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        analizador = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        bAbrir = new javax.swing.JMenuItem();
        bNuevo = new javax.swing.JMenuItem();
        bGuardar = new javax.swing.JMenuItem();
        bGComo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        bBuscar = new javax.swing.JMenuItem();
        bCopiar = new javax.swing.JMenuItem();
        bPegar = new javax.swing.JMenuItem();
        bHacer = new javax.swing.JMenuItem();
        bDeshacer = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        bReportes = new javax.swing.JMenuItem();
        bRecuento = new javax.swing.JMenuItem();
        bInfo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Linea: 1, Columna: 1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Token", "Lexema", "Linea", "Columna"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        analizador.setBackground(new java.awt.Color(0, 0, 0));
        analizador.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        analizador.setForeground(new java.awt.Color(255, 255, 255));
        analizador.setText("Analizar Texto");
        analizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(analizador)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(analizador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N

        bAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bAbrir.setText("Abrir...");
        bAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(bAbrir);

        bNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bNuevo.setText("Nuevo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(bNuevo);

        bGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(bGuardar);

        bGComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bGComo.setText("Guardar Como...");
        bGComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGComoActionPerformed(evt);
            }
        });
        jMenu1.add(bGComo);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Editar");
        jMenu2.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N

        bBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bBuscar.setText("Buscar...");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        jMenu2.add(bBuscar);

        bCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bCopiar.setText("Copiar");
        bCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCopiarActionPerformed(evt);
            }
        });
        jMenu2.add(bCopiar);

        bPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bPegar.setText("Pegar");
        bPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPegarActionPerformed(evt);
            }
        });
        jMenu2.add(bPegar);

        bHacer.setText("Hacer");
        bHacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHacerActionPerformed(evt);
            }
        });
        jMenu2.add(bHacer);

        bDeshacer.setText("Deshacer");
        bDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeshacerActionPerformed(evt);
            }
        });
        jMenu2.add(bDeshacer);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 0, 0));
        jMenu3.setText("Mostrar");
        jMenu3.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        bReportes.setText("Reportes");
        bReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReportesActionPerformed(evt);
            }
        });
        jMenu3.add(bReportes);

        bRecuento.setText("Recuento de Tokens");
        bRecuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRecuentoActionPerformed(evt);
            }
        });
        jMenu3.add(bRecuento);

        bInfo.setText("Acerca de...");
        bInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInfoActionPerformed(evt);
            }
        });
        jMenu3.add(bInfo);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 0, 0));
        jMenu4.setText("Ir a...");
        jMenu4.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo que ejecuta una accion cuando el boton abrir es presionado
    private void bAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirActionPerformed
        //Creamos el objeto JFileChooser
        JFileChooser fc = new JFileChooser();
        int seleccion = fc.showOpenDialog(this);
        // Escogemos el fichero
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            this.jTextArea1.setText("");
            File archivo = fc.getSelectedFile();
            String ruta = archivo.getAbsolutePath();
            LectorArchivo.setRuta(archivo.getAbsolutePath());
            try {
                LectorArchivo.leerArchivo(ruta, jTextArea1);
                this.setTextoGuardado(this.jTextArea1.getText());
            } catch (IOException ex) {
                Logger.getLogger(Editor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bAbrirActionPerformed

    //Metodo que ejecuta una accion cuando el boton Nuevo es presionado
    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
        if (this.getTextoGuardado().equals(this.jTextArea1.getText())) {
            this.jTextArea1.setText("");
            LectorArchivo.setRuta("");
        } else {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Deseas iniciar otro archivo sin guardar los cambios?", "Alerta", JOptionPane.YES_NO_OPTION);
            if (opcion == 0) {
                this.jTextArea1.setText("");
                LectorArchivo.setRuta("");
            }
        }
    }//GEN-LAST:event_bNuevoActionPerformed

    //Metodo que ejecuta una accion cuando el boton guardar es presionado
    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        if (LectorArchivo.getRuta().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existe una ruta para guardar los cambios");
        } else {
            LectorArchivo.guardarCambios(jTextArea1);
            this.setTextoGuardado(this.jTextArea1.getText());
        }

    }//GEN-LAST:event_bGuardarActionPerformed

    private void bGComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGComoActionPerformed
        String nombre = JOptionPane.showInputDialog("Ingresa el nombre de tu archivo") + ".txt";
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ingresaste un nombre");
        } else {
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Guardar");
            //Indicamos que solo la ruta de los directorios jale
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int seleccion = fc.showOpenDialog(this);
            //Escogemos el fichero
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                String rutaAbsoluta = fc.getSelectedFile() + File.separator + nombre;
                LectorArchivo.setRuta(rutaAbsoluta);
                LectorArchivo.guardarCambios(jTextArea1);
            }
        }
    }//GEN-LAST:event_bGComoActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        String patron = JOptionPane.showInputDialog("Ingresa la palabra a buscar");
        if (patron.isBlank()) {
            JOptionPane.showMessageDialog(null, "No ingresaste ninguna palabra");
        } else {
            try {
                VentanaTextoBuscado buscar = new VentanaTextoBuscado(patron, this.jTextArea1.getText());
            } catch (BadLocationException ex) {
                Logger.getLogger(Editor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCopiarActionPerformed
        // TODO add your handling code here:
        if (this.jTextArea1.getSelectedText() == null) {
            cyp.copiarTexto(this.jTextArea1.getText());
        } else {
            cyp.copiarTexto(this.jTextArea1.getSelectedText());
        }
    }//GEN-LAST:event_bCopiarActionPerformed

    private void bPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPegarActionPerformed
        // TODO add your handling code here:
        int posicion = this.jTextArea1.getCaretPosition();
        String textoParaPegar = cyp.pegarTexto();
        this.jTextArea1.insert(textoParaPegar, posicion);
    }//GEN-LAST:event_bPegarActionPerformed

    private void bInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Nombre del estudiante: Luis Nery Cifuentes Rodas" + "\nCarne: 202030482" + "\nIngenieria en Ciencias y Sistemas" + "\nCuarto Semestre", "Informacion del estudiante", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bInfoActionPerformed

    private void bReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReportesActionPerformed
        // TODO add your handling code here:
        LlenadoTabla.llenarTablaError(jTable1, this.bReportes);
    }//GEN-LAST:event_bReportesActionPerformed

    private void analizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizadorActionPerformed
        // TODO add your handling code here:
        if (this.jTextArea1.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "No hay texto para analizar");
        } else {
            AlmacenadorInfo.getDatosTabla().clear();
            String texto = this.jTextArea1.getText();
            stk = new Separador_Token(texto);
            while(stk.getPosicion() < texto.length()){
                stk.separarTexto();
            }
        }
    }//GEN-LAST:event_analizadorActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void bRecuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRecuentoActionPerformed
        // TODO add your handling code here:
        LlenadoTabla.recontarToken(jTable1, this.jMenu3);
    }//GEN-LAST:event_bRecuentoActionPerformed

    private void bHacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHacerActionPerformed
        // TODO add your handling code here:
        try {
          hyd.redo();
        } catch (CannotRedoException cre) {
          cre.printStackTrace();
        }
        
    }//GEN-LAST:event_bHacerActionPerformed

    private void bDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeshacerActionPerformed
        // TODO add your handling code here:
        try {
          hyd.undo();
        } catch (CannotRedoException cre) {
          cre.printStackTrace();
        }
    }//GEN-LAST:event_bDeshacerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizador;
    private javax.swing.JMenuItem bAbrir;
    private javax.swing.JMenuItem bBuscar;
    private javax.swing.JMenuItem bCopiar;
    private javax.swing.JMenuItem bDeshacer;
    private javax.swing.JMenuItem bGComo;
    private javax.swing.JMenuItem bGuardar;
    private javax.swing.JMenuItem bHacer;
    private javax.swing.JMenuItem bInfo;
    private javax.swing.JMenuItem bNuevo;
    private javax.swing.JMenuItem bPegar;
    private javax.swing.JMenuItem bRecuento;
    private javax.swing.JMenuItem bReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public String getTextoGuardado() {
        return textoGuardado;
    }

    public void setTextoGuardado(String textoGuardado) {
        this.textoGuardado = textoGuardado;
    }

}
